spring:
  datasource:
    initialize: true
#    driverClassName: "org.hibernate.spatial.dialect.postgis.PostgisDialect"
#    username: ${JDBC_DATABASE_USERNAME}
#    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace

  thymeleaf:
    cache: false
  data:
    rest:
      base-path: /api

management:
  security:
    enabled: false


#
#logging:
#  level:
##    root: "trace"
#    org:
#      springframework:
#        web:
#          servlet:
#            resource: "trace"
